import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Shield, CheckCircle2, AlertTriangle, Ban } from "lucide-react";

export default function FairPlay() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-1 py-12 px-4">
        <div className="container max-w-5xl">
          <div className="flex items-center justify-center gap-3 mb-6">
            <Shield className="h-10 w-10 text-primary" />
            <h1 className="text-4xl md:text-5xl font-bold text-center">Fair Play Policy</h1>
          </div>
          <p className="text-center text-lg text-muted-foreground mb-8">Ensuring integrity, transparency, and fairness for all users</p>

          <Alert className="mb-8 border-primary">
            <CheckCircle2 className="h-4 w-4" />
            <AlertDescription>
              <strong>Our Commitment:</strong> AYACHI Fantasy Sport is committed to maintaining a fair, transparent, and secure platform for all users.
            </AlertDescription>
          </Alert>

          <div className="space-y-6">
            <Card><CardHeader><CardTitle className="text-2xl">1. Fair Play Principles</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-lg">Fair Play is the foundation of AYACHI Fantasy Sport. We believe every user deserves an equal opportunity to participate, compete, and enjoy the platform without unfair advantages or manipulation. Our principles include: equal opportunity for all eligible users, transparent rules and scoring systems, zero tolerance for cheating or fraud, protection of user data and privacy, and consistent enforcement of policies.</p><p className="text-lg">We are committed to creating a level playing field where success is determined by cricket knowledge, strategic thinking, and analytical skills—not by exploitation of loopholes, use of unauthorized tools, or unethical practices. Fair Play ensures the integrity of contests and maintains trust within our community.</p></CardContent></Card>

            <Card><CardHeader><CardTitle className="text-2xl">2. How Fair Play Works</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-lg">We implement Fair Play through multiple mechanisms: automated monitoring systems that detect suspicious activity; manual review of flagged accounts and contests; transparent scoring algorithms based on real cricket statistics; regular audits of contest integrity; user reporting tools; and continuous policy updates based on emerging threats.</p><p className="text-lg">Our systems analyze patterns such as unusual team selections, coordinated behavior across multiple accounts, rapid account creation, and statistical anomalies. When violations are detected, we investigate thoroughly before taking action. We follow Fair Play principles in our own operations by being transparent about rules, responding to user concerns promptly, and applying penalties consistently.</p></CardContent></Card>

            <Card><CardHeader><CardTitle className="text-2xl">3. Prohibited Activities</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-lg">The following activities violate our Fair Play Policy and are strictly prohibited: creating or operating multiple accounts; using bots, scripts, or automated tools; sharing insider information or engaging in match-fixing; colluding with other users to manipulate contests; exploiting bugs or vulnerabilities; impersonating other users or providing false information; using VPNs or proxies to circumvent geographic restrictions; engaging in any form of fraud or deception.</p><p className="text-lg">These prohibitions exist to protect the integrity of the platform and ensure fair competition. Any user found engaging in prohibited activities will face immediate consequences including account suspension, permanent ban, and potential legal action. We have zero tolerance for behavior that undermines Fair Play.</p></CardContent></Card>

            <Card><CardHeader><CardTitle className="text-2xl">4. Multiple Accounts Policy</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-lg">Each user is permitted ONLY ONE account on AYACHI Fantasy Sport. Creating multiple accounts to gain unfair advantages, manipulate contests, or circumvent restrictions is strictly prohibited. Our systems actively monitor for duplicate accounts using various detection methods including email patterns, device fingerprints, IP addresses, and behavioral analysis.</p><p className="text-lg">If multiple accounts are detected, all associated accounts will be permanently banned without warning. There are no exceptions to this policy. If you forget your login credentials, use the password recovery feature rather than creating a new account. Family members sharing the same household may each have one account but must use unique email addresses and personal information.</p></CardContent></Card>

            <Card><CardHeader><CardTitle className="text-2xl">5. Collusion and Match-Fixing</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-lg">Collusion refers to users working together to gain unfair advantages in contests. This includes coordinating team selections, sharing strategies to manipulate outcomes, or any form of cooperative behavior intended to disadvantage other users. Match-fixing involves using insider information about real cricket matches to gain unfair advantages.</p><p className="text-lg">We monitor for collusion through pattern analysis, unusual correlations between user accounts, and statistical anomalies. Any evidence of collusion or match-fixing will result in permanent bans for all involved parties and potential reporting to law enforcement authorities. The integrity of real cricket matches and our fantasy contests is paramount.</p></CardContent></Card>

            <Card><CardHeader><CardTitle className="text-2xl">6. Bot and Automation Detection</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-lg">The use of bots, scripts, automated tools, or any software designed to provide unfair advantages is strictly prohibited. This includes tools that auto-select teams, scrape data, manipulate contest entries, or perform actions faster than humanly possible. Our platform is designed for human users making strategic decisions based on their cricket knowledge.</p><p className="text-lg">We employ sophisticated detection systems that identify non-human behavior patterns including abnormal speed of actions, repetitive patterns, unusual API usage, and other technical indicators. Accounts using automation tools will be immediately suspended pending investigation and permanently banned upon confirmation.</p></CardContent></Card>

            <Card><CardHeader><CardTitle className="text-2xl">7. Account Security</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-lg">Maintaining account security is a shared responsibility. You must use a strong, unique password and never share your login credentials with anyone. Enable any available security features and be cautious of phishing attempts. We will never ask for your password via email or other communication.</p><p className="text-lg">If you suspect unauthorized access to your account, immediately change your password and contact us. We monitor for suspicious login patterns and may temporarily lock accounts showing signs of compromise. Account sharing violates our Fair Play Policy and may result in account termination.</p></CardContent></Card>

            <Card><CardHeader><CardTitle className="text-2xl">8. Reporting Violations</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-lg">We encourage users to report suspected Fair Play violations. You can report concerns through our contact page or support system. Provide as much detail as possible including usernames, contest details, dates, and description of the suspected violation. All reports are treated confidentially.</p><p className="text-lg">We take all reports seriously and investigate thoroughly. While we cannot disclose investigation outcomes due to privacy concerns, we appreciate community vigilance in maintaining platform integrity. False or malicious reports made to harass other users will themselves be treated as violations.</p></CardContent></Card>

            <Card><CardHeader><CardTitle className="text-2xl">9. Investigation Process</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-lg">When a potential violation is detected or reported, we initiate a thorough investigation. This includes reviewing account activity, analyzing patterns, examining contest data, and gathering evidence. Investigations are conducted by trained personnel following established procedures to ensure fairness and accuracy.</p><p className="text-lg">During investigations, we may temporarily suspend accounts to prevent further violations. Users under investigation may be contacted for additional information. We strive to complete investigations promptly while ensuring thoroughness. All evidence is carefully evaluated before any final determination is made.</p></CardContent></Card>

            <Card><CardHeader><CardTitle className="text-2xl">10. Penalties and Consequences</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-lg">Penalties for Fair Play violations depend on severity and frequency. Consequences may include: warning for minor first-time violations; temporary account suspension (7-30 days); permanent account ban; forfeiture of contest participation; removal of teams and contest entries; and reporting to law enforcement for serious violations involving fraud or illegal activity.</p><p className="text-lg">We apply penalties consistently based on the nature and impact of violations. Repeat offenders face escalating consequences. Permanent bans are irreversible and prevent future account creation. Since our platform involves no money, there are no financial penalties, but serious violations may result in legal action.</p></CardContent></Card>

            <Card><CardHeader><CardTitle className="text-2xl">11. Appeals Process</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-lg">If you believe an account action was taken in error, you may submit an appeal within 30 days. Appeals must be submitted in writing through our contact form with a detailed explanation and any supporting evidence. We will review appeals objectively and respond within 15 business days.</p><p className="text-lg">The appeals process is not available for clear-cut violations such as multiple accounts, bot usage, or fraud. Appeals are granted only when new evidence emerges or procedural errors are identified. Our decision on appeals is final. Repeated frivolous appeals may result in communication restrictions.</p></CardContent></Card>

            <Card className="bg-primary/5"><CardHeader><CardTitle className="text-2xl">Report Violations</CardTitle></CardHeader><CardContent><p className="text-lg mb-4">Help us maintain Fair Play by reporting suspected violations:</p><div className="space-y-2"><p><strong>AYACHI HEALTHCARE PRIVATE LIMITED</strong></p><p><strong>Address:</strong> H. NO. 1/104, NEW JIA MAU, NEAR PARAG ATM, LUCKNOW, Uttar Pradesh, 226001</p><p>Together, we can ensure a fair and enjoyable experience for all users.</p></div></CardContent></Card>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
